server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/petadoption
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB    # Maximum size of a single uploaded file
      max-request-size: 20MB # Maximum total request size (including all files and form data)
  profiles:
    active: dev
upload:
  directory: "uploads"

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web: DEBUG