server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/petadoption
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB    # Maximum size of a single uploaded file
      max-request-size: 20MB # Maximum total request size (including all files and form data)
  profiles:
    active: dev
upload:
  directory: "uploads"
security:
  jwt:
    secret-key: "aad2528687ff6a9eaee35fe10bf883810427f0f0a4beb054b0ea5e8a93039941"
    expiration-time: 2592000000 # 1 week in millisecond

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web: DEBUG